version: 2.1

commands:

  checkout-all:
    steps:
      - checkout
      - run:
          name: Checkout submodules
          command: |
            git submodule update --init --recursive

  setup-build-system:
    steps:
      - run:
          name: system setup
          command: ./deps/readies/bin/getpy3

  setup-executor:
    steps:
      - run:
          name: Setup executor
          command: |
            apt-get -qq update
            apt-get -q install -y git openssh-client curl ca-certificates make tar gzip
            bash <(curl -fsSL https://get.docker.com)
      - setup_remote_docker:
          docker_layer_caching: true

jobs:

  edge-build:
    parameters:
      variant:
        type: string
      publish:
        type: string
        default: ""
    docker:
      - image: cimg/python:3.9
    steps:
      - setup_remote_docker
      - checkout-all
      - setup-build-system
      - run:
          name: Build edge for variant
          command: |
            docker login -u redisfab -p $DOCKER_REDISFAB_PWD
            make -C edge build DOCKER_SUFFIX="<parameters.variant>>" VERBOSE=1 <<parameters.variant>> <<parameters.publish>>
          no_output_timeout: 40m

on-any-branch: &on-any-branch
  filters:
    branches:
      only: /.*/
    tags:
      only: /.*/

never: &never
  filters:
    branches:
      ignore: /.*/
    tags:
      ignore: /.*/

on-master: &on-master
  filters:
    branches:
      only: master

on-version-tags: &on-version-tags
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^v[0-9].*/

on-master-and-version-tags: &on-master-and-version-tags
  filters:
    branches:
      only:
        - master
    tags:
      only: /^v[0-9].*/


workflows:
  version: 2
  default_flow:
    jobs:
      - edge-build:
          context: common
          matrix:
              parameters:
                variant:
                  - "GPU=1"
                  - "CPU=1"
          <<: *on-any-branch

  edge_nightly:
    triggers:
      - schedule:
          cron: "2 3 * * *"
          filters:
            branches:
              only: master
    jobs:
      - edge-build:
          context: common
          matrix:
            parameters:
              variant:
                - "GPU=1"
                - "CPU=1"
              publish:
                - "PUBLISH=1"
