version: 2.1

jobs:
  build-multiarch-docker:
    machine:
      enabled: true
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Setup Docker client experimental features
          command: |
            sudo ./deps/readies/bin/getdocker --just-enable-exp
            docker version
      - run:
          name: Build
          command: |
            sudo docker login -u redisfab -p $DOCKER_REDISFAB_PWD
            make -C build/docker build
            sudo make -C build/docker publish

workflows:
  version: 2
  build_and_package:
    jobs:
      - build-multiarch-docker:
          filters:
            tags:
              only: /.*/
            branches:
              only: master
