version: 2.1

build-x64:
    steps:
      - checkout
      - run:
          name: Build RedisEdge x64
          command: |
            docker build .

on-any-branch: &on-any-branch
  filters:
    branches:
      only: /.*/
    tags:
      only: /.*/

on-master: &on-master
  filters:
    branches:
      only: master
    tags:
      ignore: /.*/

workflows:
  version: 2
  build_and_package:
    jobs:
      - build-x64:
          <<: *on-any-branch
