version: 2.1

commands:
  setup-executor:
    steps:
      - run:
          name: Setup executor
          command: |
            apt-get -qq update
            apt-get -q install -y git openssh-client curl ca-certificates make tar gzip
            bash <(curl -fsSL https://get.docker.com)
      - setup_remote_docker:
          docker_layer_caching: true

  platform-build-steps:
    parameters:
      platform:
        type: string
      publish:
        type: boolean
        default: false
    steps:
      - setup-executor
      - checkout
      - run:
          name: Setup
          command: |
            git submodule update --init --recursive
            ./deps/readies/bin/getpy3
      - run:
          name: Build for platform
          command: |
            docker login -u redisfab -p $DOCKER_REDISFAB_PWD
            make build OSNICK=<<parameters.platform>>
            <<# parameters.publish >> make publish OSNICK=<<parameters.platform>> <</ parameters.publish >>
          no_output_timeout: 40m

  edge-build-steps:
    parameters:
      platform:
        type: string
    steps:
      - setup-executor
      - checkout
      - run:
          name: Setup
          command: |
            git submodule update --init --recursive
            ./deps/readies/bin/getpy3
      - run:
          name: Build for platform
          command: |
            docker login -u redisfab -p $DOCKER_REDISFAB_PWD
            for i in cpu gpu; do
              make -C edge build publish OSNICK=<<parameters.platform>> PUSH_EDGE=1 DOCKER_ORG=redislabs REDISGEARS_DOCKERDEP=edge REDISTIMESERIES_DOCKERDEP=edge REDISAI_DOCKERDEP=edge-$i VERSION=edge VARIANT=x64-$i
            done
          no_output_timeout: 40m

jobs:
  platform-build:
    parameters:
      platform:
        type: string
      publish:
        type: boolean
        default: false
    docker:
      - image: debian:buster
    steps:
      - platform-build-steps:
          platform: <<parameters.platform>>
          publish: <<parameters.publish>>

  edge-build:
    parameters:
      platform:
        type: string
    docker:
      - image: debian:buster
    steps:
      - edge-build-steps:
          platform: <<parameters.platform>>

on-any-branch: &on-any-branch
  filters:
    branches:
      only: /.*/
    tags:
      only: /.*/

never: &never
  filters:
    branches:
      ignore: /.*/
    tags:
      ignore: /.*/

on-master: &on-master
  filters:
    branches:
      only: master

on-version-tags: &on-version-tags
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^v[0-9].*/

on-master-and-version-tags: &on-master-and-version-tags
  filters:
    branches:
      only:
        - master
    tags:
      only: /^v[0-9].*/


workflows:
  version: 2
  default_flow:
    jobs:
      - platform-build:
          name: build-bionic
          platform: bionic
          publish: true
          <<: *on-any-branch

  edge_dailies:
    triggers:
      - schedule:
          cron: "2 9,18 * * *"
          filters:
            branches:
              only: master
    jobs:
      - platform-build:
          name: build-edge
          platform: bionic
