version: 2.1

commands:
  build_x64:
    steps:
      - run:
          name: Build RedisEdge x64
          command: |
            docker build .

jobs:
  build_edge_docker:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - build_x64

on-any-branch: &on-any-branch
  filters:
    branches:
      only: /.*/
    tags:
      only: /.*/

on-master: &on-master
  filters:
    branches:
      only: master
    tags:
      ignore: /.*/

workflows:
  version: 2
  build_and_package:
    jobs:
      - build_edge_docker:
          <<: *on-any-branch
